<a href="https://colab.research.google.com/github/hmdredwan/Co-Lab/blob/main/Copy_of_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Array Challenge
Create a NumPy array containing 20 random integers between 1 and 100. Then perform the following operations:
Add 10 to each element (element-wise addition)
Multiply the array by 2 (element-wise multiplication)
Calculate the mean, standard deviation, and maximum value
Reshape the array into a 4×5 matrix

In [ ]:
import numpy as np
a=np.random.randint(1,100,size=20)
print(a)
mul=a*2
print(mul)
mean_value=np.mean(a)
std_value=np.std(a)
max_value=np.max(a)
print(f"Mean : {mean_value}")
print(f"Standard Deviation : {std_value}")
print(f"Maximum Value : {max_value}")
array_reshaped= a.reshape(4,5)
print(a)
print(array_reshaped)

[ 2 57 29 70 86 56 60 96 18 89 72 38 16 12 25 94 12  3 95 68]
[  4 114  58 140 172 112 120 192  36 178 144  76  32  24  50 188  24   6
 190 136]
Mean : 49.9
Standard Deviation : 32.46367200425731
Maximum Value : 96
[ 2 57 29 70 86 56 60 96 18 89 72 38 16 12 25 94 12  3 95 68]
[[ 2 57 29 70 86]
 [56 60 96 18 89]
 [72 38 16 12 25]
 [94 12  3 95 68]]


# Pandas DataFrame Task
1. Create a DataFrame with 5 rows and 3 columns of random numbers
The DataFrame is generated from a 5x3 matrix of random integers between 1 and 100.
Display the DataFrame
2. Compute the sum of each column
The .sum() function computes the sum for each column in the DataFrame.
3. Compute the mean of each column
The .mean() function computes the mean (average) of each column in the DataFrame.


In [ ]:
import pandas as pd
import numpy as np
number=np.random.randint(1,100,size=15)
shaped_number=number.reshape(5,3)
df = pd.DataFrame(shaped_number, columns=['A', 'B', 'C'])
print(df)
a_sum=df['A'].sum()
b_sum=df['B'].sum()
c_sum=df['C'].sum()
print(a_sum)
print(b_sum)
print(c_sum)
a_mean=df['A'].mean()
b_mean=df['B'].mean()
c_mean=df['C'].mean()
print(a_mean)
print(b_mean)
print(c_mean)


    A   B   C
0   1  60  82
1  22  28   4
2  19  53  44
3   1  19  44
4  82  50  27
125
210
201
25.0
42.0
40.2
